trigger:
  branches:
    include: [master, test-me-*]
  tags:
    include: ["*"]

# Run builds nightly to catch incompatibilities with new marshmallow releases
schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight build
    branches:
      include:
        - master
    always: "true"

resources:
  repositories:
    - repository: sloria
      type: github
      endpoint: github
      name: sloria/azure-pipeline-templates
      ref: refs/heads/sloria

jobs:
  - template: job--python-tox.yml@sloria
    parameters:
      toxenvs:
        - py10-marshmallow3
      os: windows
  - template: job--python-tox.yml@sloria
    parameters:
      toxenvs:
        - lint
        - py36-marshmallowlowest
        - py10-marshmallow3
        - py10-marshmallowdev
      os: linux
  - template: job--pypi-release.yml@sloria
    parameters:
      python: "3.9"
      distributions: "sdist bdist_wheel"
      dependsOn:
        - tox_windows
        - tox_linux
