trigger:
  branches:
    include: [master, test-me-*]
  tags:
    include: ['*']

resources:
  repositories:
    - repository: sloria
      type: github
      endpoint: github
      name: sloria/azure-pipeline-templates
      ref: refs/heads/sloria

jobs:
- template: job--python-tox.yml@sloria
  parameters:
    toxenvs:
      - py37-marshmallow2
      - py37-marshmallow3
    os: windows
- template: job--python-tox.yml@sloria
  parameters:
    toxenvs:
      - lint
      - py35-marshmallow2
      - py35-marshmallow3
      - py36-marshmallow2
      - py36-marshmallow3
      - py37-marshmallow2
      - py37-marshmallow3
    os: linux
- template: job--pypi-release.yml@sloria
  parameters:
    python: "3.7"
    distributions: "sdist bdist_wheel"
    dependsOn:
      - tox_windows
      - tox_linux
