name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install --upgrade pip wheel
      - run: pip install bandit black codespell flake8 flake8-2020 flake8-bugbear
                         flake8-comprehensions isort mypy pytest pyupgrade safety
      - run: bandit --recursive --skip B101 .  # B101 is assert statements
      - run: black --check .
      - run: codespell
      - run: flake8 . --count --ignore=B408 --max-complexity=11
                      --max-line-length=110 --show-source --statistics
      - run: isort --check-only --profile black . || true
      - run: pip install -r requirements.txt || pip install --editable .
      - run: mkdir --parents --verbose .mypy_cache
      - run: mypy --ignore-missing-imports --install-types --non-interactive .
      - run: pytest . || true
      - run: pytest --doctest-modules . || true
      - run: shopt -s globstar && pyupgrade --py36-plus **/*.py || true
      - run: safety check
